version: "3.7"
services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5001:5001
    environment:
      - dev=true
    command: npm run dev